version: '3.5'

services:
  iroha-node1:
    image: hyperledger/iroha:develop
    container_name: iroha_node1
    ports:
      - "50052:50051"
      - "20001:20000"
      - "10002:10001"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg1
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=helloworld
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg1
    entrypoint: ["irohad", "--genesis_block", "/opt/iroha/genesis.block", "--config", "/opt/iroha/config1.sample", "--keypair_name", "node1"]
    volumes:
      - ./:/opt/iroha
      - blockstore1:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha_pg1:
    image: postgres:9.5
    container_name: iroha_pg1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - IROHA_POSTGRES_PASSWORD=helloworld
networks: 
  iroha-network:
    name: iroha-network
volumes:
  ccache-data:
  blockstore1: